name: Build & Deploy to surge.sh

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: build
        run: ./build.sh

      - name: Deploy to yonsei.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'yonsei.surge.sh'
          project: 'public'
          login: benelog@naver.com
          token: ${{ secrets.SURGE_TOKEN }}
